[package]
name = "test_rasterization"
version = "0.1.0"
authors = ["Dinescu Stefan <aaetherengine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"
nalgebra-glm = "0.6.0"